### ISSUE TITLE
Back HU1: Crear una cuenta

### ISSUE THREAD

**Issue by andresospina0000** [MariangelaNM/Coffee-Administration-API#5]
- [ ] Como usuario, quiero poder ingresar mi nombre, correo electrónico y una contraseña segura en los campos del formulario de registro.

- [ ] Como usuario, quiero recibir un mensaje de error si algún campo del formulario de registro está vacío o si la contraseña no es lo suficientemente segura.

- [ ] Como usuario, quiero recibir un mensaje de éxito cuando mi cuenta se haya registrado correctamente.

- [ ] Como usuario, quiero que todas las cuentas creadas tengan permisos de administrador.
